# Generated by Django 2.0.3 on 2018-03-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_key', models.IntegerField()),
                ('participant1_name', models.CharField(max_length=500)),
                ('participant2_name', models.CharField(max_length=500)),
                ('last_mes_auth_name', models.CharField(max_length=500)),
                ('last_mes_text', models.CharField(max_length=5000)),
                ('last_mes_ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=500)),
                ('sender_name', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=5000)),
                ('ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
        migrations.AddField(
            model_name='friends',
            name='fr1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
        migrations.AddField(
            model_name='friends',
            name='fr2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='last_mes_auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='participant1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='participant2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snn.Users'),
        ),
    ]
