# Generated by Django 2.0.3 on 2018-03-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='last_mes_auth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_mes_auth_id', to='snn.Users'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='participant1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant1_id', to='snn.Users'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='participant2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant2_id', to='snn.Users'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='fr1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr1_id', to='snn.Users'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='fr2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr2_id', to='snn.Users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='recipient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='snn.Users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='snn.Users'),
        ),
    ]
